apiVersion: v1
entries:
  helmet:
  - apiVersion: v2
    appVersion: 0.5.0
    created: "2023-01-02T23:59:00.743713232Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 2.2.2
    description: Helmet is a library Helm Chart for grouping common logic between
      Company.info charts. This chart is not deployable by itself.
    digest: 4952b5e1cca43747360516e7342a349d8eb959af234ccc76a7270c08da57c765
    home: https://github.com/serit/helmet/helm-charts/blob/main/charts/helmet
    keywords:
    - common
    - helper
    - template
    - function
    maintainers:
    - name: Company.info Developers
      url: https://company.info
    name: helmet
    type: library
    urls:
    - https://github.com/serit/helmet/helm-charts/releases/download/helmet-0.5.0/helmet-0.5.0.tgz
    version: 0.5.0
generated: "2023-01-02T23:59:00.743739532Z"
