{{- define "helmet.app" -}}

{{ include "helmet.configmap" . }}

{{- if .Values.image.repository }}
{{ include "helmet.deployment" . }}
{{- end }}

{{- if .Values.ingress.defaultBackend.enabled }}
{{ include "helmet.defaultBackend" . }}
{{- end }}

{{ include "helmet.hpa" . }}
{{ include "helmet.ingress" . }}

{{- if or .Values.secret.data .Values.secret.stringData }}
{{ include "helmet.secret" . }}
{{- end }}

{{ include "helmet.tls.secrets" . }}
{{ include "helmet.tls.selfsigned" . }}

{{- if and .Values.ports .Values.service.ports }}
{{ include "helmet.service" . }}
{{- end }}

{{- if .Values.ciliumNetworkPolicy.enabled }}
{{ include "helmet.ciliumNetworkPolicies" . }}
{{- end }}

{{ include "helmet.serviceaccount" . }}
{{ include "helmet.servicemonitor" . }}
{{ include "helmet.podmonitor" . }}
{{ include "helmet.sealed-secrets" . }}
{{- end }}
