{{- define "helmet.sealed-secrets" -}}
---
# to keep 'self' reference for nested loops
{{- $self := . -}}
# get env directory
{{- $env := .Values.env -}}
{{- range $path, $bytes := $self.Files.Glob (printf "sealed-secrets/%s/*" $env)}}
{{ tpl ($self.Files.Get $path) $  }}
{{- end -}}
{{- end -}}